@startuml Class Diagram

skinparam linetype ortho

skinparam package {
    BackgroundColor #DDDDDD
}

rectangle "Endpoint Layer" as endpoint_layer #EEEBDC {
    package endpoint {
    }
}

rectangle "Service Layer" as service_layer #EEEBDC {
    ' Main service
    package service {
        interface NavigationService {
            {abstract} +directions()
        }

        interface PathBuilder {
            {abstract} +with_base_path()
            {abstract} +with_coordinates()
            {abstract} +with_parameter()
            {abstract} +build()
            {abstract} +reset()
        }


        class NavigationServiceImpl {
            +directions()
        }

        class MapboxDirectionsPathBuilder

        ' Relations
        MapboxDirectionsPathBuilder --|> PathBuilder
        NavigationServiceImpl --> PathBuilder
        NavigationServiceImpl --|> NavigationService

        ' Alignment
        NavigationService -[hidden]down- NavigationServiceImpl
   }
}

rectangle "Utils" as utils_layer #EEEBDC {
    ' HTTP Client
    package http_client {
        interface HttpClient {
            {abstract} +sendRequest()
        }

        class HttpClientImpl {
            +sendRequest()
        }

        ' Relations
        HttpClientImpl --|> HttpClient

    }

    package misc {
        class CallbackWrapper<ResponseType> {
            +callback
        }
    }
}


' External dependencies
rectangle "External" as external_layer #EEEBDC{
    package ureq {
        interface Request
    }

    package axum {
    }
}


' Relations
endpoint ---> NavigationService
endpoint ---> axum

NavigationServiceImpl --> HttpClient

HttpClientImpl *-- Request


' Alignment
endpoint_layer -[hidden]down- service_layer
service_layer -[hidden]down- external_layer
utils_layer -[hidden]right- external_layer


@enduml