apiVersion: v1
kind: Service
metadata:
  name: navigation-service
spec:
  ports:
    - port: 3000
      protocol: TCP
      targetPort: 3000
  selector:
    app: navigation-pod
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: navigation-deploy
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: navigation-pod
  template:
    metadata:
      labels:
        app: navigation-pod
    spec:
      containers:
        - name: navigation-service-cont
          image: $IMAGE_NAME
          ports:
            - containerPort: 3000
              protocol: TCP
          volumeMounts:
            - name: secret-volume
              mountPath: "/run/secrets/mapbox_token"
              readOnly: true
              subPath: mapbox_token
      volumes:
        - name: secret-volume
          secret:
            secretName: mapbox-access
            items:
              - key: token
                path: mapbox_token
